services:
  postgres:
    image: postgres:16-alpine
    container_name: triviz-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: triviz
      POSTGRES_USER: engineer
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend 
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata:
